# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hermes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # Pods for hermes

  target 'hermesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hermesUITests' do
    # Pods for testing
  end

end
